# Generated by Django 4.0.1 on 2022-05-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='others',
            name='author',
        ),
    ]
