# Generated by Django 4.0.1 on 2022-05-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_others_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='author',
            field=models.IntegerField(default=0),
        ),
    ]
