# Generated by Django 4.0.1 on 2022-05-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_place_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='grade',
            field=models.TextField(default='school'),
        ),
    ]
