# Generated by Django 4.0.1 on 2022-05-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_others_id2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='seen',
        ),
        migrations.AddField(
            model_name='comment',
            name='numbers',
            field=models.IntegerField(default=0),
        ),
    ]
