# Generated by Django 4.0.1 on 2022-05-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_comment_seen_comment_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attendance',
            field=models.TextField(default='False'),
        ),
    ]
