# Generated by Django 4.0.1 on 2022-05-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub',
            field=models.TextField(default='sub'),
        ),
    ]
