# Generated by Django 4.0.1 on 2022-05-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_post_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.TextField(default='topic'),
        ),
    ]
