# Generated by Django 4.0.1 on 2022-05-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_post_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='sub',
            field=models.TextField(default='sub'),
        ),
    ]
