# Generated by Django 4.0.1 on 2022-05-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_others_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='topic',
            field=models.TextField(default='topic'),
        ),
    ]
