# Generated by Django 4.0.1 on 2022-05-16 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_others_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='validate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com', models.IntegerField(default=0)),
            ],
        ),
    ]
