# Generated by Django 4.0.1 on 2022-05-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_validate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.TextField(default='username'),
        ),
    ]
