# Generated by Django 4.0.1 on 2022-05-28 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_post_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.TextField(default='text')),
                ('subject', models.TextField(default='text')),
                ('votes', models.IntegerField(default=0)),
                ('grade', models.TextField(default='text')),
                ('description', models.TextField(default='des')),
                ('language', models.TextField(default='en')),
            ],
        ),
        migrations.CreateModel(
            name='campvedios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vedio', models.FileField(blank=True, null=True, upload_to='')),
                ('camp_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='comemnts_camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='text')),
                ('camp_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='usercamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_id', models.IntegerField(default=0)),
                ('email', models.TextField(default='email')),
            ],
        ),
    ]
