# Generated by Django 4.0.1 on 2022-05-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_camp_campvedios_comemnts_camp_usercamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='author',
            field=models.TextField(default='author'),
        ),
    ]
