# Generated by Django 4.0.1 on 2022-06-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_usercamp_author_usercamp_description_usercamp_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='code',
            field=models.TextField(default='code'),
        ),
    ]
