# Generated by Django 4.0.5 on 2022-09-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='true_fasle',
            field=models.TextField(default='F'),
        ),
    ]
