# Generated by Django 4.0.5 on 2022-09-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_worker_true_fasle'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='true_fasle',
            field=models.TextField(default='F'),
        ),
    ]
